/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./public/models/hand.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import gsap from "gsap";
import { useState } from "react";
import { useEffect } from "react";
import { useFrame } from '@react-three/fiber';
import { MeshStandardMaterial } from 'three';

export function HandModel(props) {

  const handref = useRef()
  const { nodes, materials, animations } = useGLTF('./models/hand.glb')
  const { actions } = useAnimations(animations, handref)


  useEffect(() => {
    const tween = gsap.to(handref.current.position, {
      y: '-3',
      
      yoyo: true,
      repeat: -1,
      duration: 3,
      ease: 'power1.inOut',
    });
    return () => {
      tween.kill();
    };
  }, []);

  useFrame(() => {
    // Update any other animations here
   
  });

  const [showText, setShowText] = useState(false);

  const handleMouseEnter = () => {
    gsap.to(handref.current.scale, { duration: 0.2, x: 1.7, y: 1.7, z: 1.7 });

    setShowText(true);
  };

  const handleMouseLeave = () => {
    gsap.to(handref.current.scale, { duration: 0.2, x: 1.3, y: 1.3, z: 1.3 });

    setShowText(false);
  };

  return (
   <>
    <group ref={handref} {...props} dispose={null} onPointerEnter={handleMouseEnter} onPointerLeave={handleMouseLeave}>
      <group name="Scene">
        <group name="Armature">
       
          <primitive object={nodes.pulseR} />
          <primitive object={nodes.index_tipR} />
          <primitive object={nodes.middle_tipR} />
          <primitive object={nodes.ring_tipR} />
          <primitive object={nodes.pinky_tipR} />
          <primitive object={nodes.thumb_tipR} />
          <skinnedMesh   name="handSmooth001" geometry={nodes.handSmooth001.geometry} material={materials['lambert1.001']} skeleton={nodes.handSmooth001.skeleton} />
        </group>
        <group name="Sketchfab_model" position={[-0.907, 0.727, 0.623]} rotation={[1.571, 1.53, -Math.PI]} scale={0.012}>
          <group name="10d303afd96646438dfea7a6b7c7c561fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="aguja" position={[-13.488, 50.059, -17.844]} rotation={[-Math.PI / 2, 0, -1.032]}>
                <mesh name="aguja_aguja_0" geometry={nodes.aguja_aguja_0.geometry} material={materials['aguja.001']} position={[-0.956, 0.275, -6.977]} />
              </group>
              <group name="hilo" position={[8.312, 55.411, 23.545]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="hilo_hilo_0" geometry={nodes.hilo_hilo_0.geometry} material={materials['hilo.001']} position={[-0.153, 0.568, -7.686]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    
   </>
  )
}

useGLTF.preload('./models/hand.glb')
